import type { SourceType } from '@saveus/common';

/**
 * Seed source library.
 *
 * Every entry below is a real, publicly available publication, dataset or
 * institutional programme. Titles, publishers and URLs point at the actual
 * publisher; where a permanent deep link was not certain at seed time, the URL
 * points at the publisher's landing page for that publication or series rather
 * than at a guessed path.
 *
 * What is NOT here, deliberately: invented papers, invented DOIs, invented
 * authors, and invented findings attributed to real publications. The demo
 * hypotheses and discussion that reference these records are synthetic and are
 * labelled DEMO DATA in the interface; the source records themselves are real
 * so that "follow the citation" always leads somewhere real.
 *
 * `retrieved_at` on the stored row is the seed date. It does not claim that the
 * platform fetched and parsed the document.
 */

export interface SeedSource {
  key: string;
  title: string;
  authors: string[];
  publisher: string;
  publicationDate: string | null;
  url: string;
  sourceType: SourceType;
}

export const SEED_SOURCES: readonly SeedSource[] = [
  // ---------------------------------------------------------------- climate
  {
    key: 'ipcc-ar6-wg1',
    title: 'Climate Change 2021: The Physical Science Basis (AR6 Working Group I)',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2021-08',
    url: 'https://www.ipcc.ch/report/ar6/wg1/',
    sourceType: 'UN',
  },
  {
    key: 'ipcc-ar6-wg2',
    title: 'Climate Change 2022: Impacts, Adaptation and Vulnerability (AR6 Working Group II)',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2022-02',
    url: 'https://www.ipcc.ch/report/ar6/wg2/',
    sourceType: 'UN',
  },
  {
    key: 'ipcc-ar6-wg3',
    title: 'Climate Change 2022: Mitigation of Climate Change (AR6 Working Group III)',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2022-04',
    url: 'https://www.ipcc.ch/report/ar6/wg3/',
    sourceType: 'UN',
  },
  {
    key: 'ipcc-ar6-syr',
    title: 'AR6 Synthesis Report: Climate Change 2023',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2023-03',
    url: 'https://www.ipcc.ch/report/ar6/syr/',
    sourceType: 'UN',
  },
  {
    key: 'ipcc-sr15',
    title: 'Global Warming of 1.5 °C: Special Report',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2018-10',
    url: 'https://www.ipcc.ch/sr15/',
    sourceType: 'UN',
  },
  {
    key: 'ipcc-srccl',
    title: 'Climate Change and Land: Special Report',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2019-08',
    url: 'https://www.ipcc.ch/srccl/',
    sourceType: 'UN',
  },
  {
    key: 'ipcc-srocc',
    title: 'The Ocean and Cryosphere in a Changing Climate: Special Report',
    authors: [],
    publisher: 'Intergovernmental Panel on Climate Change',
    publicationDate: '2019-09',
    url: 'https://www.ipcc.ch/srocc/',
    sourceType: 'UN',
  },
  {
    key: 'global-carbon-budget',
    title: 'Global Carbon Budget',
    authors: [],
    publisher: 'Global Carbon Project',
    publicationDate: null,
    url: 'https://www.globalcarbonproject.org/carbonbudget/',
    sourceType: 'DATASET',
  },
  {
    key: 'copernicus-c3s',
    title: 'Copernicus Climate Change Service (C3S)',
    authors: [],
    publisher: 'Copernicus / ECMWF',
    publicationDate: null,
    url: 'https://climate.copernicus.eu/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'copernicus-cds',
    title: 'Copernicus Climate Data Store (ERA5 reanalysis and derived datasets)',
    authors: [],
    publisher: 'Copernicus / ECMWF',
    publicationDate: null,
    url: 'https://cds.climate.copernicus.eu/',
    sourceType: 'DATASET',
  },
  {
    key: 'nasa-gistemp',
    title: 'GISS Surface Temperature Analysis (GISTEMP v4)',
    authors: [],
    publisher: 'NASA Goddard Institute for Space Studies',
    publicationDate: null,
    url: 'https://data.giss.nasa.gov/gistemp/',
    sourceType: 'DATASET',
  },
  {
    key: 'noaa-climate-at-a-glance',
    title: 'Climate at a Glance',
    authors: [],
    publisher: 'NOAA National Centers for Environmental Information',
    publicationDate: null,
    url: 'https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/',
    sourceType: 'DATASET',
  },
  {
    key: 'noaa-co2-trends',
    title: 'Trends in Atmospheric Carbon Dioxide',
    authors: [],
    publisher: 'NOAA Global Monitoring Laboratory',
    publicationDate: null,
    url: 'https://gml.noaa.gov/ccgg/trends/',
    sourceType: 'DATASET',
  },
  {
    key: 'climate-adapt',
    title: 'Climate-ADAPT: European Climate Adaptation Platform',
    authors: [],
    publisher: 'European Environment Agency',
    publicationDate: null,
    url: 'https://climate-adapt.eea.europa.eu/',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'nasem-negative-emissions',
    title: 'Negative Emissions Technologies and Reliable Sequestration: A Research Agenda',
    authors: [],
    publisher: 'National Academies of Sciences, Engineering, and Medicine',
    publicationDate: '2019',
    url: 'https://nap.nationalacademies.org/catalog/25259/negative-emissions-technologies-and-reliable-sequestration-a-research-agenda',
    sourceType: 'REPORT',
  },
  {
    key: 'epa-ghg-sources',
    title: 'Sources of Greenhouse Gas Emissions',
    authors: [],
    publisher: 'U.S. Environmental Protection Agency',
    publicationDate: null,
    url: 'https://www.epa.gov/ghgemissions/sources-greenhouse-gas-emissions',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'cdc-heat-tracking',
    title: 'Environmental Public Health Tracking Network (heat and health indicators)',
    authors: [],
    publisher: 'U.S. Centers for Disease Control and Prevention',
    publicationDate: null,
    url: 'https://ephtracking.cdc.gov/',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'carbon-brief',
    title: 'Carbon Brief: climate science and policy analysis',
    authors: [],
    publisher: 'Carbon Brief',
    publicationDate: null,
    url: 'https://www.carbonbrief.org/',
    sourceType: 'NEWS',
  },

  // ----------------------------------------------------------------- health
  {
    key: 'who-heat-health',
    title: 'Climate change: Heat and health',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: '2024-05',
    url: 'https://www.who.int/news-room/fact-sheets/detail/climate-change-heat-and-health',
    sourceType: 'UN',
  },
  {
    key: 'who-climate-health',
    title: 'Climate change and health (health topic)',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/health-topics/climate-change',
    sourceType: 'UN',
  },
  {
    key: 'who-air-quality',
    title: 'Ambient (outdoor) air quality and health',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health',
    sourceType: 'UN',
  },
  {
    key: 'who-household-air',
    title: 'Household air pollution and health',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health',
    sourceType: 'UN',
  },
  {
    key: 'who-amr',
    title: 'Antimicrobial resistance',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: '2023-11',
    url: 'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance',
    sourceType: 'UN',
  },
  {
    key: 'who-dengue',
    title: 'Dengue and severe dengue',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue',
    sourceType: 'UN',
  },
  {
    key: 'who-malaria',
    title: 'Malaria',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/malaria',
    sourceType: 'UN',
  },
  {
    key: 'who-ncds',
    title: 'Noncommunicable diseases',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/noncommunicable-diseases',
    sourceType: 'UN',
  },
  {
    key: 'who-ageing',
    title: 'Ageing and health',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/ageing-and-health',
    sourceType: 'UN',
  },
  {
    key: 'who-drinking-water',
    title: 'Drinking-water',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/drinking-water',
    sourceType: 'UN',
  },
  {
    key: 'who-road-traffic',
    title: 'Road traffic injuries',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/news-room/fact-sheets/detail/road-traffic-injuries',
    sourceType: 'UN',
  },
  {
    key: 'who-gho',
    title: 'Global Health Observatory',
    authors: [],
    publisher: 'World Health Organization',
    publicationDate: null,
    url: 'https://www.who.int/data/gho',
    sourceType: 'DATASET',
  },
  {
    key: 'lancet-countdown',
    title: 'The Lancet Countdown on Health and Climate Change',
    authors: [],
    publisher: 'The Lancet',
    publicationDate: null,
    url: 'https://www.thelancet.com/countdown-health-climate',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'lancet-gram-amr',
    title: 'Global burden of bacterial antimicrobial resistance in 2019: a systematic analysis',
    authors: ['Antimicrobial Resistance Collaborators'],
    publisher: 'The Lancet',
    publicationDate: '2022-02',
    url: 'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)02724-0/fulltext',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'eat-lancet',
    title: 'The EAT-Lancet Commission on Healthy Diets From Sustainable Food Systems',
    authors: [],
    publisher: 'The Lancet',
    publicationDate: '2019-01',
    url: 'https://www.thelancet.com/commissions/EAT',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'ihme-gbd',
    title: 'Global Burden of Disease Study (GBD)',
    authors: [],
    publisher: 'Institute for Health Metrics and Evaluation',
    publicationDate: null,
    url: 'https://www.healthdata.org/research-analysis/gbd',
    sourceType: 'DATASET',
  },
  {
    key: 'ecdc',
    title: 'European Centre for Disease Prevention and Control',
    authors: [],
    publisher: 'ECDC',
    publicationDate: null,
    url: 'https://www.ecdc.europa.eu/en',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'santepublique-france',
    title: 'Santé publique France: surveillance et prévention',
    authors: [],
    publisher: 'Santé publique France',
    publicationDate: null,
    url: 'https://www.santepubliquefrance.fr/',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'nih-pubmed',
    title: 'PubMed',
    authors: [],
    publisher: 'U.S. National Library of Medicine',
    publicationDate: null,
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
    sourceType: 'DATASET',
  },

  // ----------------------------------------------------------------- energy
  {
    key: 'iea-net-zero-2050',
    title: 'Net Zero by 2050: A Roadmap for the Global Energy Sector',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: '2021-05',
    url: 'https://www.iea.org/reports/net-zero-by-2050',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-weo',
    title: 'World Energy Outlook',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/topics/world-energy-outlook',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-electricity',
    title: 'Electricity (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/electricity',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-grids',
    title: 'Electricity Grids and Secure Energy Transitions',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: '2023-10',
    url: 'https://www.iea.org/reports/electricity-grids-and-secure-energy-transitions',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-critical-minerals',
    title: 'The Role of Critical Minerals in Clean Energy Transitions',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: '2021-05',
    url: 'https://www.iea.org/reports/the-role-of-critical-minerals-in-clean-energy-transitions',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-renewables',
    title: 'Renewables (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/renewables',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-solar-pv',
    title: 'Solar PV (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/renewables/solar-pv',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-wind',
    title: 'Wind (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/renewables/wind',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-hydrogen',
    title: 'Hydrogen (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/low-emission-fuels/hydrogen',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-ccus',
    title: 'Carbon Capture, Utilisation and Storage',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/carbon-capture-utilisation-and-storage',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-heat-pumps',
    title: 'Heat Pumps (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/buildings/heat-pumps',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-buildings',
    title: 'Buildings (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/buildings',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-cooling',
    title: 'Space Cooling (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/buildings/space-cooling',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-efficiency',
    title: 'Energy Efficiency and Demand',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/energy-efficiency-and-demand',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-data-centres',
    title: 'Data Centres and Data Transmission Networks',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/buildings/data-centres-and-data-transmission-networks',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-methane',
    title: 'Methane Abatement',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/fossil-fuels/methane-abatement',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'irena-publications',
    title: 'IRENA Publications (renewable capacity and cost statistics)',
    authors: [],
    publisher: 'International Renewable Energy Agency',
    publicationDate: null,
    url: 'https://www.irena.org/Publications',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'nrel-atb',
    title: 'Annual Technology Baseline (ATB)',
    authors: [],
    publisher: 'National Renewable Energy Laboratory',
    publicationDate: null,
    url: 'https://atb.nrel.gov/',
    sourceType: 'DATASET',
  },
  {
    key: 'eia-aeo',
    title: 'Annual Energy Outlook',
    authors: [],
    publisher: 'U.S. Energy Information Administration',
    publicationDate: null,
    url: 'https://www.eia.gov/outlooks/aeo/',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'doe-storage-challenge',
    title: 'Energy Storage Grand Challenge',
    authors: [],
    publisher: 'U.S. Department of Energy',
    publicationDate: null,
    url: 'https://www.energy.gov/energy-storage-grand-challenge/energy-storage-grand-challenge',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'rte-futurs-2050',
    title: 'Futurs énergétiques 2050 (Bilan prévisionnel)',
    authors: [],
    publisher: "RTE (Réseau de transport d'électricité)",
    publicationDate: '2021-10',
    url: 'https://www.rte-france.com/analyses-tendances-et-prospectives/bilan-previsionnel-2050-futurs-energetiques',
    sourceType: 'REPORT',
  },
  {
    key: 'ademe-transitions',
    title: 'Transition(s) 2050: quatre scénarios pour atteindre la neutralité carbone',
    authors: [],
    publisher: 'ADEME',
    publicationDate: '2021-11',
    url: 'https://www.ademe.fr/les-futurs-en-transition/',
    sourceType: 'GOVERNMENT',
  },

  // ------------------------------------------------------------------ water
  {
    key: 'wri-aqueduct',
    title: 'Aqueduct Water Risk Atlas',
    authors: [],
    publisher: 'World Resources Institute',
    publicationDate: null,
    url: 'https://www.wri.org/aqueduct',
    sourceType: 'DATASET',
  },
  {
    key: 'fao-aquastat',
    title: 'AQUASTAT: FAO Global Information System on Water and Agriculture',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/aquastat/en/',
    sourceType: 'DATASET',
  },
  {
    key: 'jmp-washdata',
    title: 'WHO/UNICEF Joint Monitoring Programme for Water Supply, Sanitation and Hygiene',
    authors: [],
    publisher: 'WHO/UNICEF JMP',
    publicationDate: null,
    url: 'https://washdata.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'usgs-water',
    title: 'Water Resources of the United States',
    authors: [],
    publisher: 'U.S. Geological Survey',
    publicationDate: null,
    url: 'https://www.usgs.gov/mission-areas/water-resources',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'eea-water',
    title: 'Water (European environment topic)',
    authors: [],
    publisher: 'European Environment Agency',
    publicationDate: null,
    url: 'https://www.eea.europa.eu/en/topics/in-depth/water',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'unccd',
    title: 'United Nations Convention to Combat Desertification',
    authors: [],
    publisher: 'UNCCD',
    publicationDate: null,
    url: 'https://www.unccd.int/',
    sourceType: 'UN',
  },
  {
    key: 'epa-pfas',
    title: 'PFAS Explained',
    authors: [],
    publisher: 'U.S. Environmental Protection Agency',
    publicationDate: null,
    url: 'https://www.epa.gov/pfas/pfas-explained',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'epa-drinking-water-pfas',
    title: 'Per- and Polyfluoroalkyl Substances (PFAS) drinking water regulation',
    authors: [],
    publisher: 'U.S. Environmental Protection Agency',
    publicationDate: null,
    url: 'https://www.epa.gov/sdwa/and-polyfluoroalkyl-substances-pfas',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'efsa',
    title: 'European Food Safety Authority',
    authors: [],
    publisher: 'EFSA',
    publicationDate: null,
    url: 'https://www.efsa.europa.eu/en',
    sourceType: 'INSTITUTION',
  },

  // ------------------------------------------------------------------- food
  {
    key: 'fao-sofi',
    title: 'The State of Food Security and Nutrition in the World (SOFI)',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/publications/sofi/en',
    sourceType: 'UN',
  },
  {
    key: 'fao-faostat',
    title: 'FAOSTAT',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/faostat/en/',
    sourceType: 'DATASET',
  },
  {
    key: 'fao-food-loss-platform',
    title: 'Technical Platform on the Measurement and Reduction of Food Loss and Waste',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/platform-food-loss-waste/en',
    sourceType: 'UN',
  },
  {
    key: 'fao-soils',
    title: 'Global Soil Partnership',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/global-soil-partnership/en/',
    sourceType: 'UN',
  },
  {
    key: 'fao-fisheries',
    title: 'FAO Fisheries and Aquaculture',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/fishery/en',
    sourceType: 'UN',
  },
  {
    key: 'fao-food-waste',
    title: 'Food Loss and Food Waste',
    authors: [],
    publisher: 'Food and Agriculture Organization',
    publicationDate: null,
    url: 'https://www.fao.org/food-loss-and-food-waste/en/',
    sourceType: 'UN',
  },
  {
    key: 'cgiar-research',
    title: 'CGIAR Research Portfolio',
    authors: [],
    publisher: 'CGIAR',
    publicationDate: null,
    url: 'https://www.cgiar.org/research/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'ifpri',
    title: 'International Food Policy Research Institute',
    authors: [],
    publisher: 'IFPRI',
    publicationDate: null,
    url: 'https://www.ifpri.org/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'jrc-esdac',
    title: 'European Soil Data Centre (ESDAC)',
    authors: [],
    publisher: 'Joint Research Centre, European Commission',
    publicationDate: null,
    url: 'https://esdac.jrc.ec.europa.eu/',
    sourceType: 'DATASET',
  },

  // ----------------------------------------------------------- biodiversity
  {
    key: 'ipbes-global-assessment',
    title: 'Global Assessment Report on Biodiversity and Ecosystem Services',
    authors: [],
    publisher: 'IPBES',
    publicationDate: '2019-05',
    url: 'https://www.ipbes.net/global-assessment',
    sourceType: 'UN',
  },
  {
    key: 'ipbes-invasive',
    title: 'Assessment Report on Invasive Alien Species and their Control',
    authors: [],
    publisher: 'IPBES',
    publicationDate: '2023-09',
    url: 'https://www.ipbes.net/ias',
    sourceType: 'UN',
  },
  {
    key: 'iucn-red-list',
    title: 'The IUCN Red List of Threatened Species',
    authors: [],
    publisher: 'International Union for Conservation of Nature',
    publicationDate: null,
    url: 'https://www.iucnredlist.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'cbd-gbf',
    title: 'Kunming-Montreal Global Biodiversity Framework',
    authors: [],
    publisher: 'Convention on Biological Diversity',
    publicationDate: '2022-12',
    url: 'https://www.cbd.int/gbf/',
    sourceType: 'UN',
  },
  {
    key: 'wwf-living-planet',
    title: 'Living Planet Report',
    authors: [],
    publisher: 'WWF',
    publicationDate: null,
    url: 'https://livingplanet.panda.org/',
    sourceType: 'REPORT',
  },
  {
    key: 'gbif',
    title: 'Global Biodiversity Information Facility',
    authors: [],
    publisher: 'GBIF',
    publicationDate: null,
    url: 'https://www.gbif.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'global-forest-watch',
    title: 'Global Forest Watch',
    authors: [],
    publisher: 'World Resources Institute',
    publicationDate: null,
    url: 'https://www.globalforestwatch.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'noaa-pmel-carbon',
    title: 'NOAA PMEL Carbon Program (ocean acidification)',
    authors: [],
    publisher: 'NOAA Pacific Marine Environmental Laboratory',
    publicationDate: null,
    url: 'https://www.pmel.noaa.gov/co2/',
    sourceType: 'GOVERNMENT',
  },

  // -------------------------------------------------------------- materials
  {
    key: 'unep-resource-panel',
    title: 'International Resource Panel',
    authors: [],
    publisher: 'United Nations Environment Programme',
    publicationDate: null,
    url: 'https://www.resourcepanel.org/',
    sourceType: 'UN',
  },
  {
    key: 'iea-cement',
    title: 'Cement (industry analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/industry/cement',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-steel',
    title: 'Steel (industry analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/industry/steel',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'gcca-concrete-future',
    title: 'Concrete Future: the GCCA 2050 Cement and Concrete Industry Roadmap for Net Zero',
    authors: [],
    publisher: 'Global Cement and Concrete Association',
    publicationDate: '2021-10',
    url: 'https://gccassociation.org/concretefuture/',
    sourceType: 'REPORT',
  },
  {
    key: 'materials-project',
    title: 'The Materials Project',
    authors: [],
    publisher: 'Lawrence Berkeley National Laboratory',
    publicationDate: null,
    url: 'https://next-gen.materialsproject.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'espacenet',
    title: 'Espacenet patent search',
    authors: [],
    publisher: 'European Patent Office',
    publicationDate: null,
    url: 'https://worldwide.espacenet.com/',
    sourceType: 'DATASET',
  },
  {
    key: 'wipo-patentscope',
    title: 'PATENTSCOPE',
    authors: [],
    publisher: 'World Intellectual Property Organization',
    publicationDate: null,
    url: 'https://patentscope.wipo.int/',
    sourceType: 'DATASET',
  },

  // ----------------------------------------------------------------- cities
  {
    key: 'un-habitat-wcr',
    title: 'World Cities Report',
    authors: [],
    publisher: 'UN-Habitat',
    publicationDate: null,
    url: 'https://unhabitat.org/world-cities-report',
    sourceType: 'UN',
  },
  {
    key: 'c40-knowledge',
    title: 'C40 Knowledge Hub',
    authors: [],
    publisher: 'C40 Cities',
    publicationDate: null,
    url: 'https://www.c40knowledgehub.org/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'lbnl-heat-island',
    title: 'Heat Island Group',
    authors: [],
    publisher: 'Lawrence Berkeley National Laboratory',
    publicationDate: null,
    url: 'https://heatisland.lbl.gov/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'cool-roof-rating-council',
    title: 'Cool Roof Rating Council rated products directory',
    authors: [],
    publisher: 'Cool Roof Rating Council',
    publicationDate: null,
    url: 'https://coolroofs.org/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'itree',
    title: 'i-Tree: tools for assessing urban forest benefits',
    authors: [],
    publisher: 'USDA Forest Service',
    publicationDate: null,
    url: 'https://www.itreetools.org/',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'apur',
    title: "Atelier parisien d'urbanisme (APUR)",
    authors: [],
    publisher: 'APUR',
    publicationDate: null,
    url: 'https://www.apur.org/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'insee-statistics',
    title: 'INSEE: statistiques et études',
    authors: [],
    publisher: 'Institut national de la statistique et des études économiques',
    publicationDate: null,
    url: 'https://www.insee.fr/fr/statistiques',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'globalabc',
    title: 'Global Alliance for Buildings and Construction',
    authors: [],
    publisher: 'GlobalABC / UNEP',
    publicationDate: null,
    url: 'https://globalabc.org/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'meteo-france',
    title: 'Météo-France: climat et prévisions',
    authors: [],
    publisher: 'Météo-France',
    publicationDate: null,
    url: 'https://meteofrance.fr/',
    sourceType: 'GOVERNMENT',
  },

  // -------------------------------------------------------------- transport
  {
    key: 'iea-transport',
    title: 'Transport (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/transport',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-aviation',
    title: 'Aviation (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/transport/aviation',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'iea-ev',
    title: 'Electric Vehicles (energy system analysis)',
    authors: [],
    publisher: 'International Energy Agency',
    publicationDate: null,
    url: 'https://www.iea.org/energy-system/transport/electric-vehicles',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'itf-outlook',
    title: 'ITF Transport Outlook',
    authors: [],
    publisher: 'International Transport Forum / OECD',
    publicationDate: null,
    url: 'https://www.itf-oecd.org/itf-transport-outlook',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'icct',
    title: 'International Council on Clean Transportation',
    authors: [],
    publisher: 'ICCT',
    publicationDate: null,
    url: 'https://theicct.org/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'imo-ghg',
    title: 'IMO: Marine Environment, including the GHG strategy for international shipping',
    authors: [],
    publisher: 'International Maritime Organization',
    publicationDate: null,
    url: 'https://www.imo.org/en/OurWork/Environment/Pages/Default.aspx',
    sourceType: 'UN',
  },
  {
    key: 'eea-transport',
    title: 'Transport and mobility (European environment topic)',
    authors: [],
    publisher: 'European Environment Agency',
    publicationDate: null,
    url: 'https://www.eea.europa.eu/en/topics/in-depth/transport-and-mobility',
    sourceType: 'GOVERNMENT',
  },

  // --------------------------------------------------------------------- ai
  {
    key: 'nist-ai-rmf',
    title: 'AI Risk Management Framework (AI RMF 1.0)',
    authors: [],
    publisher: 'National Institute of Standards and Technology',
    publicationDate: '2023-01',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'eu-ai-act',
    title: 'Regulation (EU) 2024/1689 laying down harmonised rules on artificial intelligence',
    authors: [],
    publisher: 'Official Journal of the European Union',
    publicationDate: '2024-07',
    url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'stanford-ai-index',
    title: 'AI Index Report',
    authors: [],
    publisher: 'Stanford Institute for Human-Centered AI',
    publicationDate: null,
    url: 'https://aiindex.stanford.edu/report/',
    sourceType: 'REPORT',
  },
  {
    key: 'arxiv-attention',
    title: 'Attention Is All You Need',
    authors: [
      'Vaswani, A.',
      'Shazeer, N.',
      'Parmar, N.',
      'Uszkoreit, J.',
      'Jones, L.',
      'Gomez, A. N.',
      'Kaiser, Ł.',
      'Polosukhin, I.',
    ],
    publisher: 'arXiv',
    publicationDate: '2017-06',
    url: 'https://arxiv.org/abs/1706.03762',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'nature-alphafold',
    title: 'Highly accurate protein structure prediction with AlphaFold',
    authors: ['Jumper, J.', 'et al.'],
    publisher: 'Nature',
    publicationDate: '2021-07',
    url: 'https://www.nature.com/articles/s41586-021-03819-2',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'nature-gnome',
    title: 'Scaling deep learning for materials discovery',
    authors: ['Merchant, A.', 'et al.'],
    publisher: 'Nature',
    publicationDate: '2023-11',
    url: 'https://www.nature.com/articles/s41586-023-06735-9',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'science-graphcast',
    title: 'Learning skillful medium-range global weather forecasting',
    authors: ['Lam, R.', 'et al.'],
    publisher: 'Science',
    publicationDate: '2023-11',
    url: 'https://www.science.org/doi/10.1126/science.adi2336',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'arxiv',
    title: 'arXiv open-access preprint archive',
    authors: [],
    publisher: 'Cornell University',
    publicationDate: null,
    url: 'https://arxiv.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'openalex',
    title: 'OpenAlex open catalogue of scholarly works',
    authors: [],
    publisher: 'OurResearch',
    publicationDate: null,
    url: 'https://openalex.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'semantic-scholar',
    title: 'Semantic Scholar',
    authors: [],
    publisher: 'Allen Institute for AI',
    publicationDate: null,
    url: 'https://www.semanticscholar.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'crossref',
    title: 'Crossref DOI registration and metadata',
    authors: [],
    publisher: 'Crossref',
    publicationDate: null,
    url: 'https://www.crossref.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'zenodo',
    title: 'Zenodo open research repository',
    authors: [],
    publisher: 'CERN / OpenAIRE',
    publicationDate: null,
    url: 'https://zenodo.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'rcsb-pdb',
    title: 'RCSB Protein Data Bank',
    authors: [],
    publisher: 'RCSB',
    publicationDate: null,
    url: 'https://www.rcsb.org/',
    sourceType: 'DATASET',
  },

  // ------------------------------------------------- long-horizon modelling
  {
    key: 'limits-to-growth',
    title:
      "The Limits to Growth: A Report for the Club of Rome's Project on the Predicament of Mankind",
    authors: ['Meadows, D. H.', 'Meadows, D. L.', 'Randers, J.', 'Behrens III, W. W.'],
    publisher: 'Club of Rome / Potomac Associates',
    publicationDate: '1972',
    url: 'https://www.clubofrome.org/publication/the-limits-to-growth/',
    sourceType: 'REPORT',
  },
  {
    key: 'club-of-rome',
    title: 'Club of Rome publications',
    authors: [],
    publisher: 'Club of Rome',
    publicationDate: null,
    url: 'https://www.clubofrome.org/publications/',
    sourceType: 'REPORT',
  },
  {
    key: 'herrington-world3',
    title: 'Update to limits to growth: Comparing the World3 model with empirical data',
    authors: ['Herrington, G.'],
    publisher: 'Journal of Industrial Ecology (Wiley)',
    publicationDate: '2021',
    url: 'https://onlinelibrary.wiley.com/doi/10.1111/jiec.13084',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'hausfather-projections',
    title: 'Evaluating the Performance of Past Climate Model Projections',
    authors: ['Hausfather, Z.', 'Drake, H. F.', 'Abbott, T.', 'Schmidt, G. A.'],
    publisher: 'Geophysical Research Letters (AGU)',
    publicationDate: '2020-01',
    url: 'https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019GL085378',
    sourceType: 'SCIENTIFIC_PAPER',
  },
  {
    key: 'charney-report',
    title: 'Carbon Dioxide and Climate: A Scientific Assessment (the Charney Report)',
    authors: [],
    publisher: 'National Academy of Sciences',
    publicationDate: '1979',
    url: 'https://nap.nationalacademies.org/catalog/12181/carbon-dioxide-and-climate-a-scientific-assessment',
    sourceType: 'REPORT',
  },
  {
    key: 'iiasa',
    title: 'IIASA: International Institute for Applied Systems Analysis',
    authors: [],
    publisher: 'IIASA',
    publicationDate: null,
    url: 'https://iiasa.ac.at/',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'planetary-boundaries',
    title: 'Planetary boundaries',
    authors: [],
    publisher: 'Stockholm Resilience Centre',
    publicationDate: null,
    url: 'https://www.stockholmresilience.org/research/planetary-boundaries.html',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'un-wpp',
    title: 'World Population Prospects',
    authors: [],
    publisher: 'United Nations Department of Economic and Social Affairs',
    publicationDate: null,
    url: 'https://population.un.org/wpp/',
    sourceType: 'UN',
  },
  {
    key: 'global-footprint-network',
    title: 'Global Footprint Network: National Footprint and Biocapacity Accounts',
    authors: [],
    publisher: 'Global Footprint Network',
    publicationDate: null,
    url: 'https://www.footprintnetwork.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'giss-publications',
    title: 'NASA GISS publications archive',
    authors: [],
    publisher: 'NASA Goddard Institute for Space Studies',
    publicationDate: null,
    url: 'https://pubs.giss.nasa.gov/',
    sourceType: 'GOVERNMENT',
  },

  // ------------------------------------------------------------ cross-cutting
  {
    key: 'un-sdgs',
    title: 'Sustainable Development Goals',
    authors: [],
    publisher: 'United Nations',
    publicationDate: null,
    url: 'https://sdgs.un.org/goals',
    sourceType: 'UN',
  },
  {
    key: 'worldbank-wdi',
    title: 'World Development Indicators',
    authors: [],
    publisher: 'World Bank',
    publicationDate: null,
    url: 'https://datatopics.worldbank.org/world-development-indicators/',
    sourceType: 'DATASET',
  },
  {
    key: 'our-world-in-data',
    title: 'Our World in Data',
    authors: [],
    publisher: 'Global Change Data Lab',
    publicationDate: null,
    url: 'https://ourworldindata.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'oecd-data',
    title: 'OECD Data Explorer',
    authors: [],
    publisher: 'OECD',
    publicationDate: null,
    url: 'https://data-explorer.oecd.org/',
    sourceType: 'DATASET',
  },
  {
    key: 'eurostat',
    title: 'Eurostat',
    authors: [],
    publisher: 'European Commission',
    publicationDate: null,
    url: 'https://ec.europa.eu/eurostat',
    sourceType: 'GOVERNMENT',
  },
  {
    key: 'nasa-earthdata',
    title: 'NASA Earthdata',
    authors: [],
    publisher: 'NASA',
    publicationDate: null,
    url: 'https://www.earthdata.nasa.gov/',
    sourceType: 'DATASET',
  },
  {
    key: 'copernicus-dataspace',
    title: 'Copernicus Data Space Ecosystem (Sentinel imagery)',
    authors: [],
    publisher: 'European Space Agency',
    publicationDate: null,
    url: 'https://dataspace.copernicus.eu/',
    sourceType: 'DATASET',
  },
  {
    key: 'nasa-power',
    title: 'NASA POWER: Prediction of Worldwide Energy Resources',
    authors: [],
    publisher: 'NASA Langley Research Center',
    publicationDate: null,
    url: 'https://power.larc.nasa.gov/',
    sourceType: 'DATASET',
  },
  {
    key: 'iucn-nbs',
    title: 'Nature-based Solutions',
    authors: [],
    publisher: 'International Union for Conservation of Nature',
    publicationDate: null,
    url: 'https://www.iucn.org/our-work/nature-based-solutions',
    sourceType: 'INSTITUTION',
  },
  {
    key: 'unep-adaptation',
    title: 'UNEP Climate Adaptation programme',
    authors: [],
    publisher: 'United Nations Environment Programme',
    publicationDate: null,
    url: 'https://www.unep.org/topics/climate-action/adaptation',
    sourceType: 'UN',
  },
];

export const SOURCE_KEYS = SEED_SOURCES.map((source) => source.key);
